routes/auth_bp.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from extensions import db
from models.user import User

auth_bp = Blueprint("auth_bp", __name__)


@auth_bp.get("/login")
def login_page():
    return render_template("login.html")


@auth_bp.get("/signup")
def signup_page():
    return render_template("signup.html")


@auth_bp.post("/login")
def submit_login_page():
    username = request.form.get("username")
    password = request.form.get("password")

    try:
        if not username:
            raise ValueError("Username must be filled")

        if not password:
            raise ValueError("Password must be filled")

        user_from_db = User.query.filter_by(username=username).first()

        if not (user_from_db and check_password_hash(user_from_db.password, password)):
            raise ValueError("Credentials not valid")

        login_user(
            user_from_db
        )  # Create token & store in cookies for that particular user

        flash("Login Successful", "success")
        return redirect(url_for("movie_list_bp.movies_page"))
    except Exception as e:
        print(e)
        db.session.rollback()
        flash(str(e), "danger")
        return redirect(url_for("auth_bp.login_page"))


@auth_bp.post("/signup")
def submit_signup_page():
    username = request.form.get("username")
    password = request.form.get("password")
    confirm = request.form.get("confirm")

    try:
        if not username:
            raise ValueError("Username must be filled")

        if not password:
            raise ValueError("Password must be filled")

        if password != confirm:
            raise ValueError("Password does not match")

        hashed_password = generate_password_hash(password)

        data = {
            "username": username,
            "password": hashed_password,
        }

        new_user = User(**data)
        db.session.add(new_user)
        db.session.commit()
        # Todo: Take them to login page
        return redirect(url_for("main_bp.hello_world"))
    except Exception as e:
        print(e)
        db.session.rollback()
        return redirect(url_for("auth_bp.signup_page"))


@auth_bp.get("/logout")
def logout_page():
    logout_user()
    return redirect(url_for("auth_bp.login_page"))

routes/movie_list_bp.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required

from extensions import db
from models.movies import Movie

movie_list_bp = Blueprint("movie_list_bp", __name__)


def get_all_movies():
    movies = Movie.query.all()
    return [movie.to_dict() for movie in movies]


@movie_list_bp.get("/")
@login_required
def movies_page():
    return render_template("movie-list.html", movies=get_all_movies())


@movie_list_bp.get("/<id>")
@login_required
def movie_details_page(id):
    movie = Movie.query.get(id)

    if movie is None:
        return render_template("not-found.html")

    return render_template("movie-details.html", movie=movie.to_dict())


@movie_list_bp.get("/new")
@login_required
def add_movie():
    return render_template("add-movie.html")


@movie_list_bp.post("/")
@login_required
def create_movie():
    data = {
        "name": request.form.get("name"),
        "poster": request.form.get("poster"),
        "rating": request.form.get("rating"),
        "summary": request.form.get("summary"),
        "trailer": request.form.get("trailer"),
    }
    new_movie = Movie(**data)

    try:
        db.session.add(new_movie)
        db.session.commit()

        # return {
        #     "message": "Movie created successfully",
        #     "data": new_movie.to_dict(),
        # }, STATUS_CODE["CREATED"]
        return redirect(url_for("movie_list_bp.movies_page"))
    except Exception:
        db.session.rollback()  # restores data, cannot be done after commit()
        return redirect(url_for("movie_list_bp.add_movie"))


@movie_list_bp.post("/<id>")
@login_required
def delete_movie_by_id(id):
    movie = Movie.query.get(id)

    if movie is None:
        return render_template("not-found.html")

    try:
        db.session.delete(movie)
        db.session.commit()

        print("Deleted", id)
        return redirect(url_for("movie_list_bp.movies_page"))
    except Exception:
        db.session.rollback()  # restores data, cannot be done after commit()
        return redirect(url_for("movie_list_bp.movies_page"))

templates/about.html
{% extends "base.html" %} {% block head_content %}

<style>
  .name-highlight {
    color: orange;
  }
</style>

{% endblock %} {% block content %}

<h1>Hey <span class="name-highlight">{{name}}</span>✒️</h1>

<ul>
  {% for hobby in hobbies %}

  <li>{{hobby}}</li>

  {% endfor %}
</ul>

{% endblock %}

templates/add-movie.html
{% extends "base.html" %} {% block head_content %}
<style>
  .add-movie-container {
    display: grid;
    place-content: center;
    min-width: 100%;
    margin-top: 3em;
  }

  .form-element {
    display: flex;
    flex-direction: column;
  }

  .form-container {
    display: flex;
    flex-direction: column;
    gap: 1em;
    width: 20em;
  }

  input[type="submit"] {
    padding: 0.75em;
    width: 100%;
    border-radius: 0.5em;
    border: 0.1em solid rgba(0, 0, 0, 0.4);
    font-family: "Roboto", sans-serif;
    background-color: #ffffff;
  }

  input[type="submit"]:hover {
    background-color: rgba(0, 0, 0, 0.9);
    color: white;
    cursor: pointer;
  }
</style>
{% endblock %} {% block content %}
<div class="add-movie-container">
  <form
    action="{{url_for('movie_list_bp.create_movie')}}"
    method="POST"
    class="form-container"
  >
    <div class="form-element">
      <label for="name">Name</label>
      <input
        type="text"
        placeholder="The Bee Movie"
        id="name"
        name="name"
        required
      />
    </div>

    <div class="form-element">
      <label for="poster">Poster</label>
      <input
        type="text"
        placeholder="https://"
        id="poster"
        name="poster"
        required
      />
    </div>

    <div class="form-element">
      <label for="Rating">Rating</label>
      <input
        type="number"
        min="0"
        max="10"
        placeholder="7"
        id="rating"
        name="rating"
        required
      />
    </div>

    <div class="form-element">
      <label for="summary">Summary</label>
      <input
        type="textarea"
        placeholder="Lorem ipsum..."
        id="summary"
        name="summary"
        required
      />
    </div>

    <div class="form-element">
      <label for="trailer">Trailer</label>
      <input
        type="text"
        placeholder="https://youtube.com/..."
        id="trailer"
        name="trailer"
        required
      />
    </div>

    <button type="submit" class="btn btn-primary">Add Movie</button>
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"
      rel="stylesheet"
    />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
      integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>
  <style>
    body {
      font-family: "Roboto", sans-serif;
      min-height: 100%;
      overflow: hidden;
    }

    ul.nav-link-container {
      display: flex;
      flex-direction: row;
      gap: 5em;
      list-style-type: none;
      padding: 0;
      margin: 0;
      justify-content: center;
      margin-top: 2em;
    }

    .nav-link-container li {
      border: 0px solid black;
      padding: 1em;
      border-radius: 3em;
      box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0.5);
      width: 10em;
      text-align: center;
    }

    .nav-link-container a {
      text-decoration: none;
      color: black;
    }

    .nav-link-container a:hover {
      text-decoration: none;
      color: rgb(0, 114, 244);
    }
  </style>

  {% block head_content %} {% endblock %}
  <body>
    <header>
      <nav>
        <ul class="nav-link-container">
          <li><a href="/">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/profile">Profile</a></li>
          <li><a href="/movie-list">Movies</a></li>
        </ul>

        <ul class="nav-link-container">
          {% if current_user.is_authenticated %}
          <li><a href="/logout">Logout</a></li>
          <li><p>{{current_user.username}}</p></li>
          {% else %}
          <li><a href="/login">Login</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div
      class="alert alert-{{ category }} alert-dismissible fade show"
      role="alert"
    >
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} {% block head_content %}

<style>
  body {
    display: grid;
    place-content: center;
  }

  .welcome {
    text-align: center;
    margin-top: 3em;
  }
</style>

{% endblock %} {% block content %}

<div class="welcome">
  <h1>Welcome to the Movie app 🎥🍿</h1>
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %} {% block head_content %}
<style>
  .form-element {
    display: flex;
    flex-direction: column;
  }

  .form-container {
    display: flex;
    flex-direction: column;
    gap: 16px;
    max-width: 500px;
  }
</style>
{% endblock %} {% block content %}

<form
  action="{{url_for('auth_bp.submit_login_page')}}"
  method="POST"
  class="form-container"
>
  <div class="form-element">
    <label for="username">Username</label>
    <input
      type="text"
      placeholder="JohnDoe"
      id="username"
      required
      name="username"
    />
  </div>
  <div class="form-element">
    <label for="password">Password</label>
    <input type="password" id="password" required name="password" />
  </div>

  <button type="submit" class="btn btn-primary">Log In</button>
</form>

{% endblock %}

templates/movie-details.html
{% extends "base.html" %} {% block head_content %}

<style>
  body {
    font-family: "Roboto", sans-serif;
  }

  .title {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }

  p {
    color: gray;
  }

  .fa-star {
    color: gold;
  }

  .movie-trailer {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    width: 100%;
    height: 70%;
    border-bottom-left-radius: 20px;
    border-bottom-right-radius: 20px;
  }

  .flex-r {
    display: flex;
    flex-direction: row;
    width: 50%;
    justify-content: space-between;
    margin-top: 35%;
    flex-wrap: wrap;
    padding: 0% 3%;
  }

  .movie-details {
    width: 100%;
  }
</style>

{% endblock %} {% block content %}

<div>
  <iframe class="movie-trailer" full src="{{movie.trailer}}" frameborder="0">
  </iframe>
</div>
<div class="flex-r">
  <div class="movie-details">
    <div class="title">
      <h1 class="movie-name">{{movie.name}}</h1>

      <h1>
        <i class="fa-solid fa-star"></i>
        <span class="rating">{{movie.rating}}</span>
      </h1>
    </div>

    <p>{{movie.summary}}</p>
  </div>
</div>

{% endblock %}

templates/movie-list.html
{% extends "base.html" %}{% block head_content %}

<style>
  body {
    font-family: "Roboto", sans-serif;
    display: grid;
    place-content: center;
    overflow: scroll;
  }

  .movie-image {
    object-fit: cover;
    border-radius: 20px;
    margin-bottom: 0;
    width: 250px;
    height: 350px;
    box-shadow: 1px 8px 9px -6px rgba(0, 0, 0, 0.6);
    -webkit-box-shadow: 1px 8px 9px -6px rgba(0, 0, 0, 0.6);
    -moz-box-shadow: 1px 8px 9px -6px rgba(0, 0, 0, 0.6);
  }

  .movie-image:hover {
    transform: scale(1.01);
    transition-duration: 0.2s;
  }

  .card {
    width: 250px;
  }

  .title {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }

  .main-grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr;
    gap: 90px;
    margin-top: 50px;
  }

  .main-flex {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    margin-top: 50px;
    justify-content: center;
    gap: 90px;
  }

  .flex-c {
    display: flex;
    flex-direction: row;
  }

  p {
    color: gray;
  }

  .fa-star {
    color: gold;
  }

  .movie-name {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>

{% endblock %} {% block content %}

<div class="main-flex">
  {% for movie in movies %}
  <div class="card">
    <img src="{{movie.poster}}" class="movie-image" />

    <div class="title">
      <h3 class="movie-name"><a href="{{movie.id}}">{{movie.name}}</a></h3>

      <h3>
        <i class="fa-solid fa-star"></i>
        <span class="rating">{{movie.rating}}</span>
      </h3>
    </div>

    <p>{{movie.summary}}</p>

    <form
      action="{{url_for('movie_list_bp.delete_movie_by_id', id=movie.id)}}"
      method="POST"
      class="form-container"
    >
      <button type="submit" class="btn btn-danger">
        <i class="fa-solid fa-trash"></i> Delete
      </button>
    </form>
  </div>
  {% endfor %}
</div>

{% endblock %}

templates/not-found.html
{% extends "base.html" %} {% block head_content %}
<style>
  .bg {
    position: absolute;
    height: 100%;
    width: 100%;
    background-image: url("https://sitechecker.pro/wp-content/uploads/2023/06/404-status-code.png");
    background-size: contain;
  }
</style>
{% endblock %} {% block content %}

<div class="bg"></div>

{% endblock %}

templates/profile.html
{% extends "base.html" %} {% block head_content %}
<style>
  body {
    font-family: "Roboto", sans-serif;
  }

  .profile-image {
    width: 100px;
    height: 100px;
    object-fit: cover;
    border-radius: 50%;
    margin-bottom: 0;
  }

  .profile-greeting-name {
    font-style: italic;
    font-weight: 700;
    font-family: "Roboto", sans-serif;
  }

  .main-grid {
    display: grid;
    place-content: center;
    text-align: center;
  }

  .flex-h {
    display: flex;
    flex-direction: column;
    gap: 50px;
    margin-top: 50px;
  }

  .verified {
    color: oklch(0.623 0.214 259.815);
  }
</style>
{% endblock %} {% block content %}

<div class="main-grid">
  <div class="flex-h">
    {% for profile in profiles %}
    <div class="card">
      <img src="{{profile.image}}" class="profile-image" />
      <p>
        Hello,
        <span class="user-name"
          >{{profile.name}} {{ "🚀" if profile.isVerified else "🎊🎊" }}</span
        >
        {% if profile.isVerified %}
        <span class="verified"><i class="fa-solid fa-circle-check"></i></span>
        {% endif %}
      </p>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/signup.html
{% extends "base.html" %} {% block head_content %}
<style>
  .form-element {
    display: flex;
    flex-direction: column;
  }

  .form-container {
    display: flex;
    flex-direction: column;
    gap: 16px;
    max-width: 500px;
  }
</style>
{% endblock %} {% block content %}

<form
  action="{{url_for('auth_bp.submit_signup_page')}}"
  method="POST"
  class="form-container"
>
  <div class="form-element">
    <label for="username">Username</label>
    <input
      type="text"
      placeholder="JohnDoe"
      id="username"
      required
      name="username"
    />
  </div>
  <div class="form-element">
    <label for="password">Password</label>
    <input type="password" id="password" required name="password" />
  </div>
  <div class="form-element">
    <label for="confirm">Confirm Password</label>
    <input type="password" id="confirm" required name="confirm" />
  </div>

  <button type="submit" class="btn btn-primary">Sign Up</button>
</form>

{% endblock %}